<a href="https://colab.research.google.com/github/saoalonsort/Natural-Language-Processing-KI-Campus/blob/main/Proyecto_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
pets = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/My project pandas/Proyecto pandas/pet_supplies.csv')

In [7]:
pets.head()

,title,averageStar,quantity,tradeAmount,wishedCount
0,Mesh Litter Spatula Poop Remover Pet Cleaning ...,0.0,9993,5 sold,0
1,Rechargeable Mini Pet Communication Small Reco...,5.0,1986,28 sold,64
2,Dog Cooling Bed Mat Summer Puppy Cushion Soft ...,4.5,529,20 sold,38
3,Automatic Pet Feeder with Active RFID Technolo...,0.0,10,0 sold,1
4,Replace Plush Cat Toy Accessories Worms Replac...,4.9,102222,"1,000+ sold",418

In [9]:
pets.shape

(1998, 5)

In [12]:
pets.iloc[9:500]

,title,averageStar,quantity,tradeAmount,wishedCount
9,3 in 1 Dog Steamer Brush Electric Spray Cat Ha...,4.7,912,"2,000+ sold",1187
10,Non-slip Cat Litter Mat With Gift Waterproof D...,4.8,275,445 sold,901
11,Dog Collapsible Bowl Folding Silicone Pet Trav...,4.9,69902,129 sold,146
12,Pet Dog Cat Paw Print Ink Kit Pad Baby Handpri...,4.7,918,500+ sold,411
13,Personalized Collar Pet ID Tag Custom Free Eng...,4.6,7883,69 sold,93
...,...,...,...,...,...
495,Puppy Big Pet Dog Cat For Bath Brush Massage W...,4.7,1101,131 sold,358
496,Pet Cat Door Holder Latch Prevents Dogs From E...,4.8,296,238 sold,175
497,Dog Whistle To Stop Barking Device Dog Copper ...,4.4,147,395 sold,131
498,New Pet Lovely Heart Sunglasses Hairpins Pet D...,5.0,65,35 sold,55
499,1 Set Cat Plush Toy Gun Plush Launcher Silent ...,4.8,14,148 sold,57

In [14]:
pets['tradeAmount']

0            5 sold
1           28 sold
2           20 sold
3            0 sold
4       1,000+ sold
           ...
1993       142 sold
1994        24 sold
1995       135 sold
1996        34 sold
1997        92 sold
Name: tradeAmount, Length: 1998, dtype: object

In [15]:
pets.loc[0]

title          Mesh Litter Spatula Poop Remover Pet Cleaning ...
averageStar                                                  0.0
quantity                                                    9993
tradeAmount                                               5 sold
wishedCount                                                    0
Name: 0, dtype: object

In [16]:
pets['title']

0       Mesh Litter Spatula Poop Remover Pet Cleaning ...
1       Rechargeable Mini Pet Communication Small Reco...
2       Dog Cooling Bed Mat Summer Puppy Cushion Soft ...
3       Automatic Pet Feeder with Active RFID Technolo...
4       Replace Plush Cat Toy Accessories Worms Replac...
                              ...
1993    Dog Birthday Party Decoration Set Pet Triangle...
1994    PuppyToothbrush Cats Toothbrush- Pet Toothbrus...
1995    Dog Toy Dogs Accessories Pet Toys Plush Toys f...
1996    Pet Dog Cat Car Seat Belt For Accessories Good...
1997    350ml/550ml Portable Dog Water Bottle Bowl Out...
Name: title, Length: 1998, dtype: object

In [17]:
pets.drop_duplicates()

,title,averageStar,quantity,tradeAmount,wishedCount
0,Mesh Litter Spatula Poop Remover Pet Cleaning ...,0.0,9993,5 sold,0
1,Rechargeable Mini Pet Communication Small Reco...,5.0,1986,28 sold,64
2,Dog Cooling Bed Mat Summer Puppy Cushion Soft ...,4.5,529,20 sold,38
3,Automatic Pet Feeder with Active RFID Technolo...,0.0,10,0 sold,1
4,Replace Plush Cat Toy Accessories Worms Replac...,4.9,102222,"1,000+ sold",418
...,...,...,...,...,...
1993,Dog Birthday Party Decoration Set Pet Triangle...,4.8,41,142 sold,134
1994,PuppyToothbrush Cats Toothbrush- Pet Toothbrus...,5.0,10,24 sold,14
1995,Dog Toy Dogs Accessories Pet Toys Plush Toys f...,4.8,1000,135 sold,614
1996,Pet Dog Cat Car Seat Belt For Accessories Good...,5.0,598,34 sold,14
1997,350ml/550ml Portable Dog Water Bottle Bowl Out...,4.9,99897,92 sold,87

In [18]:
pets['quantity'].mean()

np.float64(15040.56906906907)

In [19]:
pets['averageStar'].median()

4.7

In [23]:
pets['averageStar'] == 5.0

0       False
1        True
2       False
3       False
4       False
        ...
1993    False
1994     True
1995    False
1996     True
1997    False
Name: averageStar, Length: 1998, dtype: bool

In [24]:
pets.loc[pets['averageStar'] == 5.0]

,title,averageStar,quantity,tradeAmount,wishedCount
1,Rechargeable Mini Pet Communication Small Reco...,5.0,1986,28 sold,64
7,Cats and Dogs Pet Plush Dinosaur Toys Interact...,5.0,78,98 sold,85
29,Degradable Dog Poop Bag Dispenser LED light Wa...,5.0,8,4 sold,5
30,Dog Shock Collar - Dog Training Collar for Dog...,5.0,39990,9 sold,45
32,Dog Poop Bags Dispenser LED Light Dog Waste Ba...,5.0,35,2 sold,3
...,...,...,...,...,...
1987,1Pcs Pet Tie Mix Colors Dog Cat Striped Bow Ti...,5.0,89,23 sold,27
1988,Cute Cartoon Pet Beds for Small Medium Dogs Wi...,5.0,313014,35 sold,1145
1990,50PCS Fashion Cute Dog Bowties For Small Dog C...,5.0,20,44 sold,61
1994,PuppyToothbrush Cats Toothbrush- Pet Toothbrus...,5.0,10,24 sold,14
1996,Pet Dog Cat Car Seat Belt For Accessories Good...,5.0,598,34 sold,14

In [25]:
pets.loc[(pets['averageStar'] == 5.0) & (pets['wishedCount'] == 14)]

,title,averageStar,quantity,tradeAmount,wishedCount
528,Remote Control Toy Car Indoor Accessories Pet ...,5.0,2382,31 sold,14
646,Pet Cleaning Wipes Remove Dirt From Eyes And E...,5.0,34,10 sold,14
712,Round Head Pet Toothbrush Remove Bad Breath Ta...,5.0,61,19 sold,14
972,40pcs Pet Dog Bowtie Lace Small Dog Cat Groomi...,5.0,29,29 sold,14
1201,A mini cartoon cow plush toy for pet grinding ...,5.0,82,16 sold,14
1312,Tick Remover Tool Professional Tick Removal Tw...,5.0,291,95 sold,14
1849,Silicone Dog Treat Bag Pet Portable Dog Traini...,5.0,101,28 sold,14
1930,Bite-resistant Pet Dog Toy Rubber Ball Beef-fl...,5.0,65,26 sold,14
1994,PuppyToothbrush Cats Toothbrush- Pet Toothbrus...,5.0,10,24 sold,14
1996,Pet Dog Cat Car Seat Belt For Accessories Good...,5.0,598,34 sold,14

In [27]:
pets.loc[pets['averageStar'].isin([5.0, 4.9])]

,title,averageStar,quantity,tradeAmount,wishedCount
1,Rechargeable Mini Pet Communication Small Reco...,5.0,1986,28 sold,64
4,Replace Plush Cat Toy Accessories Worms Replac...,4.9,102222,"1,000+ sold",418
7,Cats and Dogs Pet Plush Dinosaur Toys Interact...,5.0,78,98 sold,85
11,Dog Collapsible Bowl Folding Silicone Pet Trav...,4.9,69902,129 sold,146
29,Degradable Dog Poop Bag Dispenser LED light Wa...,5.0,8,4 sold,5
...,...,...,...,...,...
1990,50PCS Fashion Cute Dog Bowties For Small Dog C...,5.0,20,44 sold,61
1992,New Pet Lovely Heart Sunglasses Hairpins Pet D...,4.9,99,49 sold,84
1994,PuppyToothbrush Cats Toothbrush- Pet Toothbrus...,5.0,10,24 sold,14
1996,Pet Dog Cat Car Seat Belt For Accessories Good...,5.0,598,34 sold,14
1997,350ml/550ml Portable Dog Water Bottle Bowl Out...,4.9,99897,92 sold,87