<a href="https://colab.research.google.com/github/saoalonsort/Natural-Language-Processing-KI-Campus/blob/main/Pr%C3%A1ctica_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd

In [26]:
pd.DataFrame({'Sales': [4000, 8000, 16000, 32000, 18000, 30000],
              'Most sold Product': ['Laptop', 'Laptop', 'Laptop', 'Tablet', 'Computer', 'Laptop']},
             index=[2000, 2005, 2010, 2015, 2020, 2025])

      Sales Most sold Product
2000   4000            Laptop
2005   8000            Laptop
2010  16000            Laptop
2015  32000            Tablet
2020  18000          Computer
2025  30000            Laptop

In [27]:
pd.Series([8, 4, 2, 3], index=['Palabras', 'Sílabas', 'Comas', 'Puntos'], name='Texto')

Palabras    8
Sílabas     4
Comas       2
Puntos      3
Name: Texto, dtype: int64

In [28]:
datos =pd.read_csv('/content/car_price_dataset.csv')

In [29]:
datos.shape

(2000, 11)

In [30]:
datos.head()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35

In [38]:
datos['Brand']

0          Ford
1       Hyundai
2           BMW
3       Hyundai
4       Hyundai
         ...
1995    Hyundai
1996     Toyota
1997    Hyundai
1998        BMW
1999      Honda
Name: Brand, Length: 2000, dtype: object

In [50]:
datos.iloc[7]

Car_ID                  8
Brand                 BMW
Model_Year           2022
Engine_Size           3.9
Fuel_Type          Petrol
Transmission    Automatic
Mileage            195932
Doors                   4
Owner_Count             1
Horsepower            369
Price             61707.4
Name: 7, dtype: object

In [51]:
datos[0:8]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
5,6,Honda,2023,3.5,Petrol,Automatic,94110,2,4,173,54182.50
6,7,BMW,2016,2.3,Petrol,Manual,7810,2,3,267,52140.50
7,8,BMW,2022,3.9,Petrol,Automatic,195932,4,1,369,61707.40

In [53]:
datos.iloc[:10, 5]

0       Manual
1       Manual
2       Manual
3    Automatic
4       Manual
5    Automatic
6       Manual
7    Automatic
8       Manual
9       Manual
Name: Transmission, dtype: object

In [54]:
datos.iloc[[0, 3, 6], 5]

0       Manual
3    Automatic
6       Manual
Name: Transmission, dtype: object

In [55]:
datos.iloc[-678]

Car_ID              1323
Brand             Toyota
Model_Year          2021
Engine_Size          1.5
Fuel_Type       Electric
Transmission      Manual
Mileage            97508
Doors                  2
Owner_Count            2
Horsepower           315
Price            48990.6
Name: 1322, dtype: object

In [56]:
datos.loc[5, 'Brand']

'Honda'

In [58]:
datos.loc[:6, ['Brand', 'Model_Year', 'Transmission']]

     Brand  Model_Year Transmission
0     Ford        2023       Manual
1  Hyundai        2018       Manual
2      BMW        2008       Manual
3  Hyundai        2017    Automatic
4  Hyundai        2012       Manual
5    Honda        2023    Automatic
6      BMW        2016       Manual

In [59]:
datos.loc[:24, ['Brand', 'Engine_Size', 'Fuel_Type']]

      Brand  Engine_Size Fuel_Type
0      Ford          1.2    Hybrid
1   Hyundai          3.2  Electric
2       BMW          2.2    Diesel
3   Hyundai          2.2    Petrol
4   Hyundai          2.4  Electric
5     Honda          3.5    Petrol
6       BMW          2.3    Petrol
7       BMW          3.9    Petrol
8       BMW          2.6  Electric
9   Hyundai          1.3  Electric
10     Ford          4.1    Petrol
11      BMW          2.1    Diesel
12    Tesla          2.7    Petrol
13  Hyundai          3.7    Diesel
14    Honda          2.3    Petrol
15     Ford          1.2    Hybrid
16    Tesla          2.5    Petrol
17    Tesla          4.8    Petrol
18    Honda          3.6  Electric
19     Ford          3.7    Diesel
20  Hyundai          3.5    Hybrid
21   Toyota          1.8    Diesel
22     Ford          2.7    Hybrid
23    Honda          4.0    Petrol
24    Tesla          1.4  Electric

In [60]:
datos.set_index('Car_ID')

,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
Car_ID,,,,,,,,,,
1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
...,...,...,...,...,...,...,...,...,...,...
1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35
1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80
1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40
1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65
2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70

In [61]:
datos['Brand'] == 'Toyota'

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996     True
1997    False
1998    False
1999    False
Name: Brand, Length: 2000, dtype: bool

In [62]:
datos. loc[datos['Brand'] == 'Toyota']

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
21,22,Toyota,2021,1.8,Diesel,Automatic,191023,2,1,154,37807.85
27,28,Toyota,2023,2.7,Electric,Manual,15435,2,4,216,55129.25
28,29,Toyota,2013,4.9,Diesel,Automatic,189983,3,3,150,47514.85
40,41,Toyota,2023,2.1,Petrol,Automatic,187877,2,1,273,45931.15
45,46,Toyota,2012,3.6,Petrol,Automatic,141984,4,4,212,42371.80
...,...,...,...,...,...,...,...,...,...,...,...
1966,1967,Toyota,2010,2.8,Petrol,Automatic,124640,2,4,374,48402.00
1968,1969,Toyota,2021,1.8,Electric,Automatic,47687,2,2,155,44018.65
1969,1970,Toyota,2012,1.0,Petrol,Automatic,182175,4,3,95,20840.25
1986,1987,Toyota,2006,4.6,Petrol,Manual,65110,4,3,329,53916.50
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80

In [65]:
datos.loc[(datos['Brand'] == 'Toyota') & (datos['Transmission'] == 'Automatic')]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
21,22,Toyota,2021,1.8,Diesel,Automatic,191023,2,1,154,37807.85
28,29,Toyota,2013,4.9,Diesel,Automatic,189983,3,3,150,47514.85
40,41,Toyota,2023,2.1,Petrol,Automatic,187877,2,1,273,45931.15
45,46,Toyota,2012,3.6,Petrol,Automatic,141984,4,4,212,42371.80
48,49,Toyota,2007,1.3,Hybrid,Automatic,164869,4,3,89,18911.55
...,...,...,...,...,...,...,...,...,...,...,...
1946,1947,Toyota,2019,4.0,Hybrid,Automatic,90637,2,2,390,67042.15
1960,1961,Toyota,2018,2.7,Petrol,Automatic,24346,2,2,162,47952.70
1966,1967,Toyota,2010,2.8,Petrol,Automatic,124640,2,4,374,48402.00
1968,1969,Toyota,2021,1.8,Electric,Automatic,47687,2,2,155,44018.65
1969,1970,Toyota,2012,1.0,Petrol,Automatic,182175,4,3,95,20840.25

In [66]:
datos.loc[(datos['Brand'] == 'Toyota') | (datos['Fuel_Type'] == 'Hybrid')]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
15,16,Ford,2023,1.2,Hybrid,Automatic,75864,2,3,226,46896.80
20,21,Hyundai,2016,3.5,Hybrid,Automatic,71188,4,4,122,47823.60
21,22,Toyota,2021,1.8,Diesel,Automatic,191023,2,1,154,37807.85
22,23,Ford,2009,2.7,Hybrid,Automatic,86718,2,2,342,50356.10
...,...,...,...,...,...,...,...,...,...,...,...
1986,1987,Toyota,2006,4.6,Petrol,Manual,65110,4,3,329,53916.50
1988,1989,Honda,2009,2.3,Hybrid,Manual,50213,3,2,271,46463.35
1989,1990,Tesla,2012,4.3,Hybrid,Manual,198065,2,1,331,52950.75
1994,1995,Ford,2020,2.4,Hybrid,Manual,167887,4,4,168,39122.65
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80

In [68]:
datos.loc[datos['Brand'].isin(['Ford', 'Toyota', 'BMW'])]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
6,7,BMW,2016,2.3,Petrol,Manual,7810,2,3,267,52140.50
7,8,BMW,2022,3.9,Petrol,Automatic,195932,4,1,369,61707.40
8,9,BMW,2010,2.6,Electric,Manual,76688,3,1,238,44992.60
...,...,...,...,...,...,...,...,...,...,...,...
1990,1991,BMW,2011,3.4,Petrol,Manual,17938,3,1,254,50765.10
1993,1994,Ford,2022,4.4,Electric,Manual,89390,4,4,179,53926.50
1994,1995,Ford,2020,2.4,Hybrid,Manual,167887,4,4,168,39122.65
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65

In [70]:
datos['Sales'] = 'NaN'
datos['Sales']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1995    NaN
1996    NaN
1997    NaN
1998    NaN
1999    NaN
Name: Sales, Length: 2000, dtype: object

In [73]:
datos.loc[datos['Brand'].isnull()]

Empty DataFrame
Columns: [Car_ID, Brand, Model_Year, Engine_Size, Fuel_Type, Transmission, Mileage, Doors, Owner_Count, Horsepower, Price, critic, Sales]
Index: []

In [74]:
datos.loc[datos['Brand'].notnull()]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price,critic,Sales
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25,everyone,NaN
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60,everyone,NaN
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40,everyone,NaN
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70,everyone,NaN
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35,everyone,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35,everyone,NaN
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80,everyone,NaN
1997,1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40,everyone,NaN
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65,everyone,NaN
1999,2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70,everyone,NaN

In [81]:
datos['indice_nuevo'] = range(len(datos), 0, -1)
datos['indice_nuevo']

0       2000
1       1999
2       1998
3       1997
4       1996
        ...
1995       5
1996       4
1997       3
1998       2
1999       1
Name: indice_nuevo, Length: 2000, dtype: int64

In [82]:
datos['Brand'].describe()

count       2000
unique         6
top       Toyota
freq         352
Name: Brand, dtype: object

In [83]:
datos['Transmission'].describe()

count          2000
unique            2
top       Automatic
freq           1018
Name: Transmission, dtype: object

In [84]:
datos['Fuel_Type'].describe()

count       2000
unique         4
top       Diesel
freq         537
Name: Fuel_Type, dtype: object

In [86]:
datos['Mileage'].mean()

np.float64(100736.9565)

In [88]:
datos['Mileage'].median()

100590.5

In [89]:
datos['Brand'].unique()

array(['Ford', 'Hyundai', 'BMW', 'Honda', 'Tesla', 'Toyota'], dtype=object)

In [90]:
datos['Brand'].value_counts()

Brand
Toyota     352
Hyundai    337
Tesla      330
Honda      329
Ford       326
BMW        326
Name: count, dtype: int64

In [93]:
datos_mileage_mean = datos['Mileage'].mean()
datos['Mileage'].map(lambda p: p - datos_mileage_mean)

0       79898.0435
1      -65108.9565
2      -26064.9565
3      -49490.9565
4       46496.0435
           ...
1995    54296.0435
1996   -75692.9565
1997     3635.0435
1998    57310.0435
1999   -81030.9565
Name: Mileage, Length: 2000, dtype: float64

In [94]:
datos_mileage_median = datos['Mileage'].median()
datos['Mileage'].map(lambda p: p - datos_mileage_median)

0       80044.5
1      -64962.5
2      -25918.5
3      -49344.5
4       46642.5
         ...
1995    54442.5
1996   -75546.5
1997     3781.5
1998    57456.5
1999   -80884.5
Name: Mileage, Length: 2000, dtype: float64

In [97]:
def remean_mileage(row):
  row['Mileage'] = row['Mileage'] - datos_mileage_mean
  return row

datos.apply(remean_mileage, axis='columns')

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price,critic,Sales,indice_nuevo
0,1,Ford,2023,1.2,Hybrid,Manual,79898.0435,4,3,82,34309.25,everyone,NaN,2000
1,2,Hyundai,2018,3.2,Electric,Manual,-65108.9565,2,4,259,55153.60,everyone,NaN,1999
2,3,BMW,2008,2.2,Diesel,Manual,-26064.9565,3,2,333,41894.40,everyone,NaN,1998
3,4,Hyundai,2017,2.2,Petrol,Automatic,-49490.9565,4,4,381,54046.70,everyone,NaN,1997
4,5,Hyundai,2012,2.4,Electric,Manual,46496.0435,3,4,290,38010.35,everyone,NaN,1996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,54296.0435,2,3,310,61734.35,everyone,NaN,5
1996,1997,Toyota,2023,1.4,Petrol,Manual,-75692.9565,2,4,271,48467.80,everyone,NaN,4
1997,1998,Hyundai,2022,4.1,Diesel,Manual,3635.0435,4,3,191,55714.40,everyone,NaN,3
1998,1999,BMW,2020,4.4,Diesel,Automatic,57310.0435,4,1,186,53222.65,everyone,NaN,2
1999,2000,Honda,2012,1.7,Electric,Automatic,-81030.9565,3,1,165,40687.70,everyone,NaN,1

In [98]:
def remean_mileage(row):
  row['Mileage'] = row['Mileage'] - datos_mileage_median
  return row

datos.apply(remean_mileage, axis='columns')

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price,critic,Sales,indice_nuevo
0,1,Ford,2023,1.2,Hybrid,Manual,80044.5,4,3,82,34309.25,everyone,NaN,2000
1,2,Hyundai,2018,3.2,Electric,Manual,-64962.5,2,4,259,55153.60,everyone,NaN,1999
2,3,BMW,2008,2.2,Diesel,Manual,-25918.5,3,2,333,41894.40,everyone,NaN,1998
3,4,Hyundai,2017,2.2,Petrol,Automatic,-49344.5,4,4,381,54046.70,everyone,NaN,1997
4,5,Hyundai,2012,2.4,Electric,Manual,46642.5,3,4,290,38010.35,everyone,NaN,1996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,54442.5,2,3,310,61734.35,everyone,NaN,5
1996,1997,Toyota,2023,1.4,Petrol,Manual,-75546.5,2,4,271,48467.80,everyone,NaN,4
1997,1998,Hyundai,2022,4.1,Diesel,Manual,3781.5,4,3,191,55714.40,everyone,NaN,3
1998,1999,BMW,2020,4.4,Diesel,Automatic,57456.5,4,1,186,53222.65,everyone,NaN,2
1999,2000,Honda,2012,1.7,Electric,Automatic,-80884.5,3,1,165,40687.70,everyone,NaN,1

In [99]:
datos.head()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price,critic,Sales,indice_nuevo
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25,everyone,NaN,2000
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60,everyone,NaN,1999
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40,everyone,NaN,1998
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70,everyone,NaN,1997
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35,everyone,NaN,1996

In [100]:
datos_mileage_mean = datos['Mileage'].mean()
datos['Mileage'] - datos_mileage_mean

0       79898.0435
1      -65108.9565
2      -26064.9565
3      -49490.9565
4       46496.0435
           ...
1995    54296.0435
1996   -75692.9565
1997     3635.0435
1998    57310.0435
1999   -81030.9565
Name: Mileage, Length: 2000, dtype: float64

In [103]:
datos['Brand'] + "-" + datos['Transmission']

0             Ford-Manual
1          Hyundai-Manual
2              BMW-Manual
3       Hyundai-Automatic
4          Hyundai-Manual
              ...
1995       Hyundai-Manual
1996        Toyota-Manual
1997       Hyundai-Manual
1998        BMW-Automatic
1999      Honda-Automatic
Length: 2000, dtype: object